export default defineEventHandler(() => {
  return [
    {
      id: 1,
      attributes: {
        title: "Casa en venta",
        excerpt: "Precio: $500,000 MXN",
        slug: "casa-palmas",
        body: "<strong>Precio: </strong> $500,000 MXN",
        createdAt: "2022-11-07T22:07:44.308Z",
        updatedAt: "2022-11-13T03:57:54.051Z",
        publishedAt: "2022-11-07T22:07:45.775Z",
        locale: "es-MX",
        image: {
          data: {
            id: 2,
            attributes: {
              name: "casa-palmas-1.jpeg",
              alternativeText: "casa-palmas-1.jpeg",
              caption: "casa-palmas-1.jpeg",
              width: 2560,
              height: 1707,
              formats: {
                large: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "casa-palmas-1_001",
                  mime: "image/jpeg",
                  name: "casa-palmas-1.jpeg",
                  path: null,
                  size: 132.15,
                  width: 1000,
                  height: 667,
                },
                small: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "small_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "small_terreno-1.jpeg",
                  path: null,
                  size: 33.83,
                  width: 500,
                  height: 333,
                },
                medium: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "medium_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "medium_terreno-1.jpeg",
                  path: null,
                  size: 74.33,
                  width: 750,
                  height: 500,
                },
                thumbnail: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "thumbnail_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "thumbnail_terreno-1.jpeg",
                  path: null,
                  size: 8.44,
                  width: 234,
                  height: 156,
                },
              },
              hash: "terreno_1_251cd636f7",
              ext: ".jpeg",
              mime: "image/jpeg",
              size: 761.35,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:18:28.989Z",
              updatedAt: "2022-11-12T21:18:28.989Z",
            },
          },
        },
      },
      gallery: [
        {
          data: {
            id: 2,
            attributes: {
              name: "casa-palmas-1.jpeg",
              alternativeText: "casa-palmas-1.jpeg",
              caption: "casa-palmas-1.jpeg",
              width: 2560,
              height: 1707,
              formats: {
                large: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "casa-palmas-1_001",
                  mime: "image/jpeg",
                  name: "casa-palmas-1.jpeg",
                  path: null,
                  size: 132.15,
                  width: 1000,
                  height: 667,
                },
                small: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "small_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "small_terreno-1.jpeg",
                  path: null,
                  size: 33.83,
                  width: 500,
                  height: 333,
                },
                medium: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "medium_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "medium_terreno-1.jpeg",
                  path: null,
                  size: 74.33,
                  width: 750,
                  height: 500,
                },
                thumbnail: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
                  hash: "thumbnail_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "thumbnail_terreno-1.jpeg",
                  path: null,
                  size: 8.44,
                  width: 234,
                  height: 156,
                },
              },
              hash: "terreno_1_251cd636f7",
              ext: ".jpeg",
              mime: "image/jpeg",
              size: 761.35,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/1.jpeg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:18:28.989Z",
              updatedAt: "2022-11-12T21:18:28.989Z",
            },
          },
        },
        {
          data: {
            id: 2,
            attributes: {
              name: "casa-palmas-1.jpeg",
              alternativeText: "casa-palmas-1.jpeg",
              caption: "casa-palmas-1.jpeg",
              width: 2560,
              height: 1707,
              formats: {
                large: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/2.jpeg",
                  hash: "casa-palmas-1_001",
                  mime: "image/jpeg",
                  name: "casa-palmas-1.jpeg",
                  path: null,
                  size: 132.15,
                  width: 1000,
                  height: 667,
                },
                small: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/2.jpeg",
                  hash: "small_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "small_terreno-1.jpeg",
                  path: null,
                  size: 33.83,
                  width: 500,
                  height: 333,
                },
                medium: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/2.jpeg",
                  hash: "medium_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "medium_terreno-1.jpeg",
                  path: null,
                  size: 74.33,
                  width: 750,
                  height: 500,
                },
                thumbnail: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/2.jpeg",
                  hash: "thumbnail_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "thumbnail_terreno-1.jpeg",
                  path: null,
                  size: 8.44,
                  width: 234,
                  height: 156,
                },
              },
              hash: "terreno_1_251cd636f7",
              ext: ".jpeg",
              mime: "image/jpeg",
              size: 761.35,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/2.jpeg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:18:28.989Z",
              updatedAt: "2022-11-12T21:18:28.989Z",
            },
          },
        },
        {
          data: {
            id: 2,
            attributes: {
              name: "casa-palmas-1.jpeg",
              alternativeText: "casa-palmas-1.jpeg",
              caption: "casa-palmas-1.jpeg",
              width: 2560,
              height: 1707,
              formats: {
                large: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/3.jpeg",
                  hash: "casa-palmas-1_001",
                  mime: "image/jpeg",
                  name: "casa-palmas-1.jpeg",
                  path: null,
                  size: 132.15,
                  width: 1000,
                  height: 667,
                },
                small: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/3.jpeg",
                  hash: "small_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "small_terreno-1.jpeg",
                  path: null,
                  size: 33.83,
                  width: 500,
                  height: 333,
                },
                medium: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/3.jpeg",
                  hash: "medium_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "medium_terreno-1.jpeg",
                  path: null,
                  size: 74.33,
                  width: 750,
                  height: 500,
                },
                thumbnail: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/3.jpeg",
                  hash: "thumbnail_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "thumbnail_terreno-1.jpeg",
                  path: null,
                  size: 8.44,
                  width: 234,
                  height: 156,
                },
              },
              hash: "terreno_1_251cd636f7",
              ext: ".jpeg",
              mime: "image/jpeg",
              size: 761.35,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/3.jpeg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:18:28.989Z",
              updatedAt: "2022-11-12T21:18:28.989Z",
            },
          },
        },
        {
          data: {
            id: 2,
            attributes: {
              name: "casa-palmas-1.jpeg",
              alternativeText: "casa-palmas-1.jpeg",
              caption: "casa-palmas-1.jpeg",
              width: 2560,
              height: 1707,
              formats: {
                large: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/4.jpeg",
                  hash: "casa-palmas-1_001",
                  mime: "image/jpeg",
                  name: "casa-palmas-1.jpeg",
                  path: null,
                  size: 132.15,
                  width: 1000,
                  height: 667,
                },
                small: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/4.jpeg",
                  hash: "small_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "small_terreno-1.jpeg",
                  path: null,
                  size: 33.83,
                  width: 500,
                  height: 333,
                },
                medium: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/4.jpeg",
                  hash: "medium_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "medium_terreno-1.jpeg",
                  path: null,
                  size: 74.33,
                  width: 750,
                  height: 500,
                },
                thumbnail: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/4.jpeg",
                  hash: "thumbnail_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "thumbnail_terreno-1.jpeg",
                  path: null,
                  size: 8.44,
                  width: 234,
                  height: 156,
                },
              },
              hash: "terreno_1_251cd636f7",
              ext: ".jpeg",
              mime: "image/jpeg",
              size: 761.35,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/4.jpeg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:18:28.989Z",
              updatedAt: "2022-11-12T21:18:28.989Z",
            },
          },
        },
      ],
      features: [
        {
          name: "Casa en venta",
          description:
            "El frente 16m, al este 32m, al norte 10m y al oeste 19m. Excelente oportunidad para tí.",
          image:
            "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa-palmas/3.jpeg",
          imagePosition: "right",
          imageAlt: "Logo Jebem",
          theme: "", // default
          items: [
            {
              title: "Dirección",
              description:
                "Calle Halaltun s/n entre Hocolwitz y Oxpecmul. CP: 24640",
            },
            {
              title: "Precio de venta",
              description: "$500,000 MXN",
            },
            {
              title: "Contácto",
              description: "983 332 1375",
            },
          ],
        },
      ],
    },
    /*
    {
      id: 2,
      attributes: {
        title: "Terreno en el centro",
        excerpt: "Venta: $1,300 MXN",
        slug: "terreno-en-el-centro",
        body: "Terreno en xpujil <strong>centro</strong>",
        createdAt: "2022-11-07T22:07:44.308Z",
        updatedAt: "2022-11-13T03:57:54.051Z",
        publishedAt: "2022-11-07T22:07:45.775Z",
        locale: "es-MX",
        image: {
          data: {
            id: 2,
            attributes: {
              name: "terreno-1.jpeg",
              alternativeText: "terreno-1.jpeg",
              caption: "terreno-1.jpeg",
              width: 2560,
              height: 1707,
              formats: {
                large: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/terreno.jpeg",
                  hash: "large_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "large_terreno-1.jpeg",
                  path: null,
                  size: 132.15,
                  width: 1000,
                  height: 667,
                },
                small: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/terreno.jpeg",
                  hash: "small_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "small_terreno-1.jpeg",
                  path: null,
                  size: 33.83,
                  width: 500,
                  height: 333,
                },
                medium: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/terreno.jpeg",
                  hash: "medium_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "medium_terreno-1.jpeg",
                  path: null,
                  size: 74.33,
                  width: 750,
                  height: 500,
                },
                thumbnail: {
                  ext: ".jpeg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/terreno.jpeg",
                  hash: "thumbnail_terreno_1_251cd636f7",
                  mime: "image/jpeg",
                  name: "thumbnail_terreno-1.jpeg",
                  path: null,
                  size: 8.44,
                  width: 234,
                  height: 156,
                },
              },
              hash: "terreno_1_251cd636f7",
              ext: ".jpeg",
              mime: "image/jpeg",
              size: 761.35,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/terreno.jpeg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:18:28.989Z",
              updatedAt: "2022-11-12T21:18:28.989Z",
            },
          },
        },
      },
    },
    {
      id: 3,
      attributes: {
        title: "Casa en colonia Xmaben",
        excerpt: "Precio: $400,000 MXN\nContácto: 983-130-3499",
        slug: "casa-en-colonia-xmaben",
        body: "Dirección: Colonia Xmaben #459 <br>\nWhatsapp: <strong>999-231-0101</strong>",
        createdAt: "2022-11-12T21:20:53.869Z",
        updatedAt: "2022-11-13T03:55:19.168Z",
        publishedAt: "2022-11-12T21:21:13.725Z",
        locale: "es-MX",
        image: {
          data: {
            id: 3,
            attributes: {
              name: "el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
              alternativeText:
                "el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
              caption:
                "el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
              width: 2268,
              height: 1322,
              formats: {
                large: {
                  ext: ".jpg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa.jpg",
                  hash: "large_el_terreno_que_piensas_comprar_sirve_para_construir_verificalo_asi_83c6d7166f",
                  mime: "image/jpeg",
                  name: "large_el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
                  path: null,
                  size: 59.84,
                  width: 1000,
                  height: 583,
                },
                small: {
                  ext: ".jpg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa.jpg",
                  hash: "small_el_terreno_que_piensas_comprar_sirve_para_construir_verificalo_asi_83c6d7166f",
                  mime: "image/jpeg",
                  name: "small_el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
                  path: null,
                  size: 19.8,
                  width: 500,
                  height: 291,
                },
                medium: {
                  ext: ".jpg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa.jpg",
                  hash: "medium_el_terreno_que_piensas_comprar_sirve_para_construir_verificalo_asi_83c6d7166f",
                  mime: "image/jpeg",
                  name: "medium_el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
                  path: null,
                  size: 37.5,
                  width: 750,
                  height: 437,
                },
                thumbnail: {
                  ext: ".jpg",
                  url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa.jpg",
                  hash: "thumbnail_el_terreno_que_piensas_comprar_sirve_para_construir_verificalo_asi_83c6d7166f",
                  mime: "image/jpeg",
                  name: "thumbnail_el-terreno-que-piensas-comprar-sirve-para-construir-verificalo-asi.jpg",
                  path: null,
                  size: 6.31,
                  width: 245,
                  height: 143,
                },
              },
              hash: "el_terreno_que_piensas_comprar_sirve_para_construir_verificalo_asi_83c6d7166f",
              ext: ".jpg",
              mime: "image/jpeg",
              size: 238.54,
              url: "https://qzxcfcpyemrhuakuymvj.supabase.co/storage/v1/object/public/jebem/casa.jpg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
              createdAt: "2022-11-12T21:20:48.551Z",
              updatedAt: "2022-11-12T21:20:48.551Z",
            },
          },
        },
      },
    },
    */
  ];
});
